<a href="https://colab.research.google.com/github/muhammadraudhatul/JST_2311532013/blob/main/TugasPertemuan7JST_2311532013.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
df = pd.read_csv("ObesityDataSet.csv")
print("Data shape:", df.shape)
print(df.head())

Data shape: (2111, 17)
   Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public

In [ ]:
# Pisahkan fitur dan target
X = df.drop(columns=['NObeyesdad'])
y = df['NObeyesdad']

# Encode kolom kategorikal
for col in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Encode label target
le_y = LabelEncoder()
y = le_y.fit_transform(y)

In [ ]:
# 4. Normalisasi fitur numerik
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 5. Split data menjadi train dan test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:

# Bangun model Neural Network
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # hidden layer 1
    Dense(32, activation='relu'),                                   # hidden layer 2
    Dense(len(np.unique(y)), activation='softmax')                  # output layer
])

# Kompilasi model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Latih model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

# Evaluasi model
y_pred = np.argmax(model.predict(X_test), axis=1)

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)



Epoch 1/50


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.2935 - loss: 1.9034 - val_accuracy: 0.4556 - val_loss: 1.5815
Epoch 2/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4984 - loss: 1.4696 - val_accuracy: 0.5828 - val_loss: 1.2507
Epoch 3/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6158 - loss: 1.1427 - val_accuracy: 0.6361 - val_loss: 1.0210
Epoch 4/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6863 - loss: 0.8929 - val_accuracy: 0.6982 - val_loss: 0.8715
Epoch 5/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7312 - loss: 0.7669 - val_accuracy: 0.7456 - val_loss: 0.7673
Epoch 6/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7757 - loss: 0.6582 - val_accuracy: 0.7781 - val_loss: 0.6924
Epoch 7/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8020 - loss: 0.5866 - val_accuracy: 0.7870 - val_loss: 0.6344
Epoch 8/50
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8317 - loss: 0.5185 - val_accuracy: 0.7988 - val_loss: 0.5870
Epo

In [ ]:
print("\n=== Hasil Evaluasi Model ===")
print(f"Akurasi: {acc:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_y.classes_))

# Analisis singkat
print("\n=== Analisis Kinerja Model ===")
print("""
Model memiliki dua hidden layer dengan aktivasi ReLU dan output softmax.
Jika akurasi dan F1-score tinggi, berarti model mampu mengenali pola obesitas dengan baik.
Jika F1-score rendah di beberapa kelas, kemungkinan karena data tidak seimbang (class imbalance),
maka dapat dicoba metode seperti oversampling atau tuning hyperparameter (jumlah neuron, learning rate, epoch, dsb).
""")


=== Hasil Evaluasi Model ===
Akurasi: 0.9243
F1-Score: 0.9248
Confusion Matrix:
 [[51  3  0  0  0  0  0]
 [ 2 49  0  0  0  7  0]
 [ 0  0 69  0  0  1  0]
 [ 0  0  2 58  0  0  0]
 [ 0  0  0  1 64  0  0]
 [ 0  6  1  0  0 49  2]
 [ 0  1  2  0  0  4 51]]

Classification Report:
                      precision    recall  f1-score   support

Insufficient_Weight       0.96      0.94      0.95        54
      Normal_Weight       0.83      0.84      0.84        58
     Obesity_Type_I       0.93      0.99      0.96        70
    Obesity_Type_II       0.98      0.97      0.97        60
   Obesity_Type_III       1.00      0.98      0.99        65
 Overweight_Level_I       0.80      0.84      0.82        58
Overweight_Level_II       0.96      0.88      0.92        58

           accuracy                           0.92       423
          macro avg       0.92      0.92      0.92       423
       weighted avg       0.93      0.92      0.92       423


=== Analisis Kinerja Model ===

Model memiliki du